
package swing;


public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rounded_Panel1 = new swing.Rounded_Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rounded_Panel2 = new swing.Rounded_Panel();
        jProgressBar1 = new javax.swing.JProgressBar();
        rounded_Panel3 = new swing.Rounded_Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rounded_Panel5 = new swing.Rounded_Panel();

        setBackground(new java.awt.Color(236, 236, 236));
        setLayout(new java.awt.CardLayout());

        rounded_Panel1.setBackground(new java.awt.Color(247, 247, 247));
        rounded_Panel1.setRoundBottomLeft(70);
        rounded_Panel1.setRoundTopLeft(70);
        rounded_Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        rounded_Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setText("Hello, Welcome Back Whiskerer");
        rounded_Panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        rounded_Panel2.setBackground(new java.awt.Color(255, 255, 255));
        rounded_Panel2.setRoundBottomLeft(50);
        rounded_Panel2.setRoundBottomRight(50);
        rounded_Panel2.setRoundTopLeft(50);
        rounded_Panel2.setRoundTopRight(50);

        javax.swing.GroupLayout rounded_Panel2Layout = new javax.swing.GroupLayout(rounded_Panel2);
        rounded_Panel2.setLayout(rounded_Panel2Layout);
        rounded_Panel2Layout.setHorizontalGroup(
            rounded_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rounded_Panel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        rounded_Panel2Layout.setVerticalGroup(
            rounded_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rounded_Panel2Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        rounded_Panel1.add(rounded_Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 200, 230));

        rounded_Panel3.setBackground(new java.awt.Color(255, 255, 255));
        rounded_Panel3.setRoundBottomLeft(50);
        rounded_Panel3.setRoundBottomRight(50);
        rounded_Panel3.setRoundTopLeft(50);
        rounded_Panel3.setRoundTopRight(50);

        javax.swing.GroupLayout rounded_Panel3Layout = new javax.swing.GroupLayout(rounded_Panel3);
        rounded_Panel3.setLayout(rounded_Panel3Layout);
        rounded_Panel3Layout.setHorizontalGroup(
            rounded_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        rounded_Panel3Layout.setVerticalGroup(
            rounded_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        rounded_Panel1.add(rounded_Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 390, 210));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        rounded_Panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 590, 250));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("WhiskerWare Manager");
        rounded_Panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel4.setText("Penjelasan Tentang WhiskerWare");
        rounded_Panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        rounded_Panel5.setBackground(new java.awt.Color(255, 255, 255));
        rounded_Panel5.setRoundBottomLeft(50);
        rounded_Panel5.setRoundBottomRight(50);
        rounded_Panel5.setRoundTopLeft(50);
        rounded_Panel5.setRoundTopRight(50);

        javax.swing.GroupLayout rounded_Panel5Layout = new javax.swing.GroupLayout(rounded_Panel5);
        rounded_Panel5.setLayout(rounded_Panel5Layout);
        rounded_Panel5Layout.setHorizontalGroup(
            rounded_Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rounded_Panel5Layout.setVerticalGroup(
            rounded_Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        rounded_Panel1.add(rounded_Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 200, 230));

        add(rounded_Panel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private swing.Rounded_Panel rounded_Panel1;
    private swing.Rounded_Panel rounded_Panel2;
    private swing.Rounded_Panel rounded_Panel3;
    private swing.Rounded_Panel rounded_Panel5;
    // End of variables declaration//GEN-END:variables
}
